trigger:
- task: SnykSecurityScan@1
  inputs:
    testType: 'app'
    monitorWhen: 'always'
    failOnIssues: true
- main  # Runs the pipeline when code is pushed to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use a Linux VM with Docker installed

stages:
- stage: SecurityScan
  displayName: "Run OWASP ZAP Scan"
  jobs:
  - job: Run_ZAP
    steps:
    
    - script: |
        docker pull owasp/zap2docker-stable
      displayName: 'Pull ZAP Docker Image'

    - script: |
        docker run --rm -v $(System.DefaultWorkingDirectory):/zap/wrk/ \
        owasp/zap2docker-stable zap-full-scan.py -t http://testphp.vulnweb.com/ -r zap_report.html
      displayName: 'Run OWASP ZAP Scan'

    - task: PublishBuildArtifacts@1
      displayName: 'Upload ZAP Report'
      inputs:
        pathToPublish: 'zap_report.html'
        artifactName: 'ZAP_Report'